# Generated by Django 5.1.3 on 2024-12-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.TextField(max_length=50),
        ),
    ]
